version: '3.8' #versão do composer
services:
  laravel:
    environment:
      - APP_ENV=staging
    container_name: eventos-homolog # nome do container para o docker
    image: php:8.2-apache # imagem usada
    working_dir: /var/www/html/ # define essa pasta como padrão num docker exec
    build:
      context: . # inicialização
      dockerfile: Dockerfile # Usa o Dockerfile (da mesma pasta) como base
    ports:
      - 8002:80 # da porta 80(DOCKER(DENTRO)) para a porta 8002(EXTERNO(VM))
    networks:
      - laravel_network_homolog
    volumes:
      - .:/var/www/html # copia do henriquedois(PC) para html(DOCKER)
    depends_on:
      - mysql #depende do banco pra subir

  mysql:
    container_name: banco-homolog
    image: mysql:8.0 # imagem para o banco de dados
    environment: # variaveis de ambiente 
      MYSQL_DATABASE: 'henriquedb10' # nome do banco a ser usado
      MYSQL_ROOT_PASSWORD: 'uniabat3' # senha do root
    #ports:
    #  - "3307:3306"
    networks:
      - laravel_network_homolog
    volumes:
      - .docker/dbdata-stage:/var/lib/mysql/ 
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  phpmyadmin:
    container_name: ocr_phpmyadmin-homolog
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: uniabat3
    ports:
      - "9092:80"
    depends_on:
      - mysql
    networks:
      - laravel_network_homolog

#volumes:
#  dbdata:
#    driver: local
networks:
  laravel_network_homolog:
    driver: bridge