version: '3.8' #versão do composer
services:
  laravel:
    container_name: eventos # nome do container para o docker
    image: php:8.2-apache # imagem usada
    working_dir: /var/www/html/ # define essa pasta como padrão num docker exec
    build:
      context: . # ?
      dockerfile: Dockerfile # Usa o Dockerfile (da mesma pasta) como base
    ports:
      - 8001:80 # da porta 80(DOCKER(DENTRO)) para a porta 8001(EXTERNO(VM))
    networks:
      - laravel_network
    volumes:
      -  /var/www/henriquedois:/var/www/html/ # copia do henriquedois(PC) para html(DOCKER)
    depends_on:
      - mysql #depende do banco pra subir

  mysql:
    image: mysql:8.0 # imagem para o banco de dados
    environment: # variaveis de ambiente 
      MYSQL_DATABASE: henriquedb10 # nome do banco a ser usado
      MYSQL_USER: 'root' # user
      MYSQL_PASSWORD: 'uniabat3' # senha
      MYSQL_ROOT_PASSWORD: 'uniabat3' # senha do root
    ports:
      - "3307:3306"
    networks:
      - laravel_network
    volumes:
      - dbdata:/var/lib/mysql 

volumes:
  dbdata:
networks:
  laravel_network: