version: '3.8'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/henriquedois
    ports:
      - 81:80
    networks:
      backend:
        aliases:
          - laravel-app

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=uniabat3
      - MYSQL_DATABASE=henriquedb10
    networks:
      backend:
        aliases:
          - db

networks:
  backend:
    name: backend-network
