version: '3.8' #versão do composer
services:
  laravel:
    environment:
      - "APP_ENV=development"
      - "DB_CONNECTION=mysql"
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "DB_DATABASE=henriquedb10"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=uniabat3"
    container_name: eventos-dev # nome do container para o docker
    image: docker.io/henriquemg/gcs-laravel:latest # imagem usada
    build:
      context: . # inicialização
      dockerfile: Dockerfile # Usa o Dockerfile (da mesma pasta) como base
    ports:
      - 8003:80 # da porta 80(DOCKER(DENTRO)) para a porta 8001(EXTERNO(VM))
    networks:
      - laravel_network_dev
    volumes:
      - .:/var/www/html # copia do henriquedois(PC) para html(DOCKER)
    depends_on:
      - mysql #depende do banco pra subir

  mysql:
    container_name: banco-dev
    image: mysql:8.0 # imagem para o banco de dados
    environment: # variaveis de ambiente 
      MYSQL_DATABASE: 'henriquedb10' # nome do banco a ser usado
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'uniabat3' # senha do root
    #ports:
    #  - "3307:3306"
    networks:
      - laravel_network_dev
    healthcheck:
            test: ["CMD-SHELL", 'mysql -uroot --database=henriquedb10 --password=uniabat3 --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
            interval: 10s
            timeout: 10s
            retries: 4
    volumes:
      - .docker/dbdata-dev:/var/lib/mysql/ 
      - ./mysql/my.cnf:/etc/mysql/my.cnf

#volumes:
#  dbdata:
#    driver: local
networks:
  laravel_network_dev:
    driver: bridge